### ISSUE TITLE
add snapshot support for lvm-localpv

### ISSUE THREAD

**Issue by pawanpraka1** [openebs/lvm-localpv#10]
**Describe the problem/challenge you have**

We want to be able to create a snapshot of the lvm volumes.

**Comment by akhilerm** [comment]
@pawanpraka1 , I can take up this issue.

**Comment by pawanpraka1** [comment]
thanks @akhilerm. Please look at this PR for reference https://github.com/openebs/zfs-localpv/pull/39.
