### ISSUE TITLE
LVM-LocalPV should pick the node where enough space is available for immediate binding

### ISSUE THREAD

**Issue by pawanpraka1** [openebs/lvm-localpv#104]
Currently for the immediate binding case we have two scheduling logic 
1. Volumeweighted, here we pick the node where less number of volumes are provisioned
2. CapacityWeighted here we pick the node where size of all the provisioned volumes are less

These 2 are not sufficient as there is a possibility of getting a node where enough space is not availabe as none of above scheduling logic look for the free space available in the volumegroup.

Now that since we have lvmnode CR which has all the information about the volume group. We can use that to find the best node. We need to create a node map (https://github.com/openebs/lvm-localpv/blob/d4c4bebc81c9f6f955c0d03f0cc2fb991c6cf374/pkg/driver/schd_helper.go#L96) of free space in the volume group. We should make this as default option for scheduling.

The schedule currently picks the node which one less weighted(https://github.com/openebs/lib-csi/blob/develop/pkg/scheduler/scheduler.go#L81) in the map, we need to modify it to pick the highest weighted node as here we need to pick the node where free space is more.

**Comment by flokli** [comment]
This is also a problem with heterogenous clusters, where some nodes don't (yet) have the VG created.

`openebs-lvm-controller` keeps trying to create the volume on a node where the volume group doesn't even exist, and keeps failing (and also doesn't seem to take taints into consideration, preventing a pod from getting scheduled there).

**Comment by pawanpraka1** [comment]
fixed via https://github.com/openebs/lvm-localpv/pull/178.

**Comment by abhilashshetty04** [comment]
> This is also a problem with heterogenous clusters, where some nodes don't (yet) have the VG created.
> 
> `openebs-lvm-controller` keeps trying to create the volume on a node where the volume group doesn't even exist, and keeps failing (and also doesn't seem to take taints into consideration, preventing a pod from getting scheduled there).

@flokli , We have created an enhancement ticket https://github.com/openebs/lvm-localpv/issues/312. It has some additional suggestions also. Please take a look.
