### ISSUE TITLE
When custom node Labels has been deleted, LVM LocalPV CSI driver will not schedule the PV to the node

### ISSUE THREAD

**Issue by huangfangfeng** [openebs/lvm-localpv#105]
**What steps did you take and what happened:**

- Currently, all custom node Labels will be registered when restart the LVM-LocalPV Driver, CSI node topologyKeys will keep all those keys even if node labels has been changed. When custom node Labels has been deleted, LVM LocalPV CSI driver will not schedule the PV to the node, restart the LVM-LocalPV Driver daemon set is a must requirement.

**What did you expect to happen:**

- That is not a reasonable way to register the topologyKeys, because it can't predict Labels deleted.

**The output of the following commands will help us better understand what's going on**:

    # kubectl logs -n kube-system openebs-lvm-controller-0  -c csi-provisioner

    E0619 07:43:46.123145       1 controller.go:984] error syncing claim "3ad3265d-8479-4485-a7ec-977b585afa19": failed to provision volume with StorageClass "local-lvm": error generating accessibility requirements: topology labels from selected node map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:node1 kubernetes.io/os:linux node-role.kubernetes.io/master: node-role.kubernetes.io/node: openebs.io/nodename:node1] does not match topology keys from CSINode [beta.kubernetes.io/arch beta.kubernetes.io/os **test** kubernetes.io/arch kubernetes.io/hostname node-role.kubernetes.io/master node-role.kubernetes.io/node openebs.io/nodename]

    # kubectl get csinode node1 -o yaml
    ......
        topologyKeys:
        - beta.kubernetes.io/arch
        - beta.kubernetes.io/os
        - test
        - kubernetes.io/arch
        - kubernetes.io/hostname
        - kubernetes.io/os
        - node-role.kubernetes.io/master
        - node-role.kubernetes.io/node
        - openebs.io/nodename

**Describe the solution you'd like:**
Is that a better way to register topologyKeys from env rather than all the custom node labels?
When you need to change topologyKeys, just modify env and restart LVM-LocalPV Driver.

**Comment by pawanpraka1** [comment]
> When you need to change topologyKeys, just modify env and restart LVM-LocalPV Driver.

@huangfangfeng this is interesting. The way you have described above, the LVM driver works exactly the same way. Once you add/remove the label, you need to restart the node agent pod running on that node and topology keys should be updated accordingly.

Did you try to restart the LVM driver daemonset running on nodes where you have modified the node label?

**Comment by huangfangfeng** [comment]
> > When you need to change topologyKeys, just modify env and restart LVM-LocalPV Driver.
> 
> @huangfangfeng this is interesting. The way you have described above, the LVM driver works exactly the same way. Once you add/remove the label, you need to restart the node agent pod running on that node and topology keys should be updated accordingly.
> 
> Did you try to restart the LVM driver daemonset running on nodes where you have modified the node label?

I don't want to restart the node agent pod when node label change, especially i cant't predit all the delete action, unless i watch the node label modify, and that's a big expenses.

**Comment by pawanpraka1** [comment]
> especially i cant't predit all the delete action
Can you elaborate your use case? Generally customers label the node once only.

**Comment by huangfangfeng** [comment]
> > Can you elaborate your use case? Generally customers label the node once only.

1. some other third-party component will add labels to node
2. our usage scenarios include some scheduling strategy that depend on node label and that label will change if node resource change.

**Comment by pawanpraka1** [comment]
@huangfangfeng, I see that you have a PR for this, would you like to upstream it?

**Comment by pawanpraka1** [comment]
fixed via https://github.com/openebs/lvm-localpv/pull/110.
