### ISSUE TITLE
miss csistoragecapacity object.

### ISSUE THREAD

**Issue by taozix** [openebs/lvm-localpv#140]
**Describe the problem/challenge you have**
did not see object csistoragecapacity in kube-system when enable storageCapacity in csidriver.

**Environment:**
- LVM Driver version: 0.8.0
- Kubernetes version (use `kubectl version`): 1.21.3
- Kubernetes installer & version: kubeadm
- other:
-kubectl get pods -n kube-system -l role=openebs-lvm
NAME                       READY   STATUS    RESTARTS   AGE
openebs-lvm-controller-0   5/5     Running   0          99m
openebs-lvm-node-2txsf     2/2     Running   0          99m
openebs-lvm-node-4mjxh     2/2     Running   0          99m
openebs-lvm-node-kr5jb     2/2     Running   0          99m

**Comment by w3aman** [comment]
@taozix I see you have used Immediate binding mode in your storage-class. You should be using `WaitForFirstConsumer` as volume binding mode in sc yaml. Can you please try with that once ?

` volumeBindingMode: WaitForFirstConsumer`

Note: Please use updated Yaml from this PR.

I've Added `--enable-capacity=true` in csi-provisioner along with `POD_NAME` env.

**Comment by taozix** [comment]
kubectl -n kube-system get csistoragecapacity 
NAME          CREATED AT
csisc-b6w9n   2021-08-31T02:23:20Z
csisc-hfktr   2021-08-31T02:23:20Z
csisc-zn6kk   2021-08-31T02:23:20Z

cool!
