### ISSUE TITLE
lvm-operator.yaml in release doesn't pin container version

### ISSUE THREAD

**Issue by flokli** [openebs/lvm-localpv#161]
**What steps did you take and what happened:**
I deployed according to the readme, which directs me to `kubectl apply -f deploy/lvm-operator.yaml`.

**What did you expect to happen:**
I checked out a specific tag/release (0.8.5 in that case). I expected the yaml file to pin that version.

However, https://github.com/openebs/lvm-localpv/blob/lvm-localpv-0.8.5/deploy/lvm-operator.yaml#L1258 uses the `ci` image tag.

I'd expect a release to pin the version used explicitly, or the release artifacts to include a rendered lvm-operator.yaml file for that specific release.

**Comment by arianvp** [comment]
The release artifact; as per release instructions  (https://openebs.github.io/charts/lvm-operator.yaml) does have the version pinned.

There is also an lvm chart in https://openebs.github.io/charts that has the version pinned (https://github.com/openebs/lvm-localpv/tree/develop/deploy/helm/charts)

**Comment by pawanpraka1** [comment]
@flokli the installation step (https://github.com/openebs/lvm-localpv#installation) uses the artifact with the proper release tag. Can you use this operator yaml : https://openebs.github.io/charts/lvm-operator.yaml.

**Comment by flokli** [comment]
Yes, but these are not named with a version themselves, so https://openebs.github.io/charts/lvm-operator.yaml could point to a new version tomorrow.

**Comment by flokli** [comment]
Is there a versioned URL, that contains the properly versioned container images in the manifests?

**Comment by pawanpraka1** [comment]
@flokli we add it here https://github.com/openebs/charts/blob/gh-pages/versioned/3.0.0/lvm-operator.yaml. But this one is based on OpenEBS release version, as you can see in above operator yaml, lvm 0.8.2 is part of Openebs 3.0.0 release.

**Comment by flokli** [comment]
Thanks, this is good enough!

I wonder if https://github.com/openebs/lvm-localpv#installation should also link to the versioned ones.

**Comment by pawanpraka1** [comment]
@flokli would you like to add that in the installation steps?

**Comment by flokli** [comment]
PR is up at https://github.com/openebs/lvm-localpv/pull/162
