### ISSUE TITLE
support for multiple volume group within a given node

### ISSUE THREAD

**Issue by iyashu** [openebs/lvm-localpv#17]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
Do we have any plans to support multiple volume groups within a storage class? As of now, I see there is `volgroup` parameter is being used by controller that one specifies in the storage class. But I think there is no way to specify multiple volume groups exists in a node to provision the logical volumes. It may be required if one is using multiple disks within a node of same type. Rather than creating single vg group across all disks of same type which introduces single point of failure with degradation of one disk affecting all lvs (lvm stripping), we would like to use multiple vgs.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Instead of understanding a single parameter `volgroup`, we can add an ability to specify a volume group name regex to use for provisioning the logical volume. In the node agent side, we can first list all vgs available on the node matching the regex & capacity requirement and then choose some vg (based on say with some configurable bin packing algo) to provision the lv. One simple bin-packing algo could be to choose vg having smallest size available to fit the required lv size.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- LVM Driver version
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by pawanpraka1** [comment]
need to understand one thing here, we don't need to create single vg group across all the disks. Why can't we create multiple vg groups and create storageclasses for each vg group and use them?

**Comment by iyashu** [comment]
@pawanpraka1 disks are fluid in nature i.e they can added or removed as per the capacity requirement of the cluster. Creating separate storage classes for each disks will require users to update their manifest/pvcs. Note here we are talking about disks of exactly same type (e.g ssd with same hardware spec).

**Comment by pawanpraka1** [comment]
ok, so user will create vg groups using the same kind of disks with name having some common patterns. And now we need to create on single storageclass with the vg group pattern and later we will decide which vg group to pick among all the matching vg group. He can label the nodes where these vg group is present and use the topology contraints in the storageclass. This sounds good, good to have this feature.
