### ISSUE TITLE
Use SpaceWeighted as the default scheduler

### ISSUE THREAD

**Issue by nkwangleiGIT** [openebs/lvm-localpv#188]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.]
As we introduced a new SpaceWeighted scheduler, and it can do better LVM volume binding, see the details in the PR below:
https://github.com/openebs/lvm-localpv/pull/178
But the default is still CapacityWeighted as we set the default value when initialize the params.

**What did you expect to happen:**
Use SpaceWeighted as the default scheduler.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other [Pastebin](https://pastebin.com/) is fine.)

* `kubectl logs -f openebs-lvm-controller-0 -n kube-system -c openebs-lvm-plugin`
* `kubectl logs -f openebs-lvm-node-[xxxx] -n kube-system -c openebs-lvm-plugin`
* `kubectl get pods -n kube-system`
* `kubectl get lvmvol -A -o yaml`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- LVM Driver version: v0.9.0
- Kubernetes version (use `kubectl version`): K8S 1.20.x
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by dsharma-dc** [comment]
@abhilashshetty04  This can perhaps be closed if the enhancement is already merged as seen from linked PR?

**Comment by abhilashshetty04** [comment]
@dsharma-dc , Yes we are using spaceWeighted algorithm by default. Closing this issue.
