### ISSUE TITLE
Why does openebs-lvm-controller use StatefulSet ?

### ISSUE THREAD

**Issue by iswbm** [openebs/lvm-localpv#196]
When the node where openebs-lvm-controller is located goes down, the pod of lvm-controller will always be in terminating and will not be automatically started on other nodes.

So I  wonder why does openebs-lvm-controller use StatefulSet ?

Are there any special considerations?

**Comment by niladrih** [comment]
I remember a discussion where this decision was made. But I just cannot recall the reason at the moment. @pawanpraka1 @akhilerm @shubham14bajpai @kmova -- is there a reason for this decision?

**Comment by evgkrsk** [comment]
Vote for Deployment.

**Comment by dsharma-dc** [comment]
@niladrih This issue can be closed now I think because the type has been changed to Deployment in PR #286 ?

**Comment by niladrih** [comment]
This was fixed in v1.5.0 and is a part of OpenEBS 4.0.
