### ISSUE TITLE
delete pvc and pv success,but lv is not automatically deleted

### ISSUE THREAD

**Issue by ptthon** [openebs/lvm-localpv#197]
**What steps did you take and what happened:**
1. Create a pvc 
2. Delete the pvc 
3. Delete the pv (association of PVC)

**What did you expect to happen:**
1. pvc and pv is delete successfully
2. lv is delete,but I can find the lv on the machine still
--- Logical volume ---
  LV Path                /dev/lvmvg/pvc-530f82a7-c8bf-4c8f-83e6-6adf5e75ac12
  LV Name                pvc-530f82a7-c8bf-4c8f-83e6-6adf5e75ac12
  VG Name                lvmvg
  LV UUID                GA0GAT-5mWw-jtEP-XRLk-A6Mf-TW1j-jA6NHY
  LV Write Access        read/write
  LV Creation host, time mgt3, 2022-06-17 15:43:04 +0800
  LV Status              available
  # open                 0
  LV Size                15.00 GiB
  Current LE             3840
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           253:16

**Environment:**
- LVM Driver version is 0.9.0
- Kubernetes version is 
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13-21", GitCommit:"6da8c0d7a77590f911e8c07e1596a34ab9c6bf4e", GitTreeState:"archive", BuildDate:"2022-02-17T07:13:59Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13-21", GitCommit:"6da8c0d7a77590f911e8c07e1596a34ab9c6bf4e", GitTreeState:"archive", BuildDate:"2022-02-17T07:13:59Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic

**Comment by npu21** [comment]
Ran into this issue days ago too

**Comment by artarik** [comment]
Did you delete LVMVolume ?

**Comment by bxy4543** [comment]
You need to check whether your storageclass.reclaimPolicy is `Delete`.

**Comment by dsharma-dc** [comment]
As indicated above, it's related to reclaimPolicy in storage class, which if set to `Retain` will not delete the underlying volume. Also I notice that in step3 it's mentioned as `delete PV`.  This shouldn't be required.
In case of a `Retain` policy , the PV status will simply change to `Released`.

I'll go ahead closing this issue now. Please feel free to reopen with details/logs required to help e.g. provisioner logs.

**Comment by dsharma-dc** [comment]
It would also be good to understand deletions were indeed done in the same order as mentioned in issue description, or there could have a race in running deletion or order swapped. It's possible that the below k8s issue could have possibly caused this :
https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/2644-honor-pv-reclaim-policy/README.md

If you still encounter it, please let us know.
