### ISSUE TITLE
RFE: automate creation of PV and VG

### ISSUE THREAD

**Issue by phhutter** [openebs/lvm-localpv#200]
**Describe the problem/challenge you have**
When using the OpenEBS lvm localpv provisioner we have to manually create one or more PV(s) and assign them to a VG. To allow a full end to end automation, we would like to have this task done by an operator.

**Describe the solution you'd like**
The creation of a PV and VG should be automated. An operator should look for a disk (e.g. /dev/sdb) or a disk metadata pattern (Vendor=xy) and create the PV and the corresponding VG. As an extension, the operator should also realize when a new disk gets added/resized to the system and pull them into the existing VG.

**Anything else you would like to add:**
Maybe thats something the NDM operator could do for us.
Is there a reason why this feature hasn't been implemented yet?

**Comment by Abhinandan-Purkait** [comment]
@phhutter We don't have any plans to include this. Also these would need a arch design.
