### ISSUE TITLE
PodSecurityPolicy is deprecated since k8s 1.21

### ISSUE THREAD

**Issue by phhutter** [openebs/lvm-localpv#201]
**Describe the problem/challenge you have**
The PodSecurityPolicy is deprecated since 1.21 and will be removed in Kubernetes 1.25. 

src: https://kubernetes.io/docs/concepts/security/pod-security-policy/

**Solution**
use SecurityContextConstraints instead

**Comment by Abhinandan-Purkait** [comment]
@phhutter Since we have already updated to latest versions. This might not be valid any more. Please reopen if you face any issue.
