### ISSUE TITLE
make the installation of snapshot.storage.k8s.io CRDs optional

### ISSUE THREAD

**Issue by phhutter** [openebs/lvm-localpv#203]
Hi,

Could we make the installation of the following CRDs optional?

https://github.com/openebs/lvm-localpv/blob/develop/deploy/helm/charts/crds/volumesnapshotclasses.yaml
https://github.com/openebs/lvm-localpv/blob/develop/deploy/helm/charts/crds/volumesnapshotcontents.yaml
https://github.com/openebs/lvm-localpv/blob/develop/deploy/helm/charts/crds/volumesnapshots.yaml

Is there a reason why you have included them in the openEBS helmchart? These resources are usually maintained and managed by the underlying kubernetes distribution. In case of OpenShift, it will automatically revert back the modifications made by your helmchart. This could be problematic if you use ArgoCD and have it on autosync.

**Comment by abhilashshetty04** [comment]
Done in https://github.com/openebs/lvm-localpv/pull/243
