### ISSUE TITLE
Requesting an update on the FOSSA licensing issue

### ISSUE THREAD

**Issue by michaeloreillyintel** [openebs/lvm-localpv#207]
The Github mentions that there are 22 issues found with the licenses for this repo.

Is there anyone looking at resolving the problems as many organisations would be wary of adopting this codebase as-is.

**Comment by pawanpraka1** [comment]
@michaeloreillyintel we need prioritize this item.

**Comment by michaeloreillyintel** [comment]
I find it hard to figure out what items are being flagged. It says 22 issues. Are you just missing license headers on files within the repo, or are these from imported dependencies?

**Comment by dsharma-dc** [comment]
@michaeloreillyintel This issue looks pretty old, but I'm going through all the issues on this repo.
Where does github it say 22 items flagged? I don't find anything under Security section.

**Comment by tiagolobocastro** [comment]
IIRC we resolved the FOSSA licensing issues a while back, please reopen if you find otherwise.
