### ISSUE TITLE
Need to support LVM striping

### ISSUE THREAD

**Issue by npu21** [openebs/lvm-localpv#208]
**Describe the problem/challenge you have**
LVM support stripping for better I/O performance using striped logical volume when there‘re number of disks 
So，if lvm-localpv support this will be a useful feature
![image](https://user-images.githubusercontent.com/11768607/191234078-1cb38ecd-244b-4751-b1b4-68110de7847a.png)

**Describe the solution you'd like**
The storage class add parameters regarding 

1. if open stripping support
2. the strip number

**Anything else you would like to add:**
This function also needs modification
![image](https://user-images.githubusercontent.com/11768607/191233673-63e74933-62f9-45eb-b61e-97757a084714.png)

**Comment by frasmarco** [comment]
Nice to have for mee too

**Comment by giusepperagusa** [comment]
I second this: striping support would be ideal for me too!

**Comment by dung-tien-nguyen** [comment]
I face the same issue. This is really necessary.

**Comment by abhilashshetty04** [comment]
@npu21 Thanks for the feature request. We have not planned to implement this as of now. However, would like to know if you want to contribute?

**Comment by giusepperagusa** [comment]
Unfortunately, I currently cannot commit any time to contribute, but I would simply like to state here that a well-known (albeit neither flexible nor automated) workaround is to use Linux software (mdadm) RAID0 to pre-create a single striped PV for the VG given to lvm-localpv

**Comment by avishnu** [comment]
Tracking this via #259
