### ISSUE TITLE
Is it safe to have manual created LVs on localpv-managed VGs?

### ISSUE THREAD

**Issue by psi-4ward** [openebs/lvm-localpv#209]
Hi,
I've some VGs where lvm-localpv acquires LVs. Is it safe to have some LVs which in the same VG which are generated manually (ie `lvcreate -L1G my-lv vg0`)?

Does lvm-localpv leave these LVs at it is? Does it have impact to capacity calculation? 

 Thx ;)

**Comment by ymwang7** [comment]
I've Execute on the host to manual created LVs on localpv-managed VGs, find lvm-localpv auto create lvs is auto deleted，you know how to solve this question?

**Comment by mnlipp** [comment]
My question exactly! (Shouldn't be that hard to answer.)

**Comment by avishnu** [comment]
Shouldn't be a problem IMO, but this needs to be tested.
@mnlipp @psi-4ward Have you been able to try the scenario and check if there were any issues?
Thanks in advance.

**Comment by mnlipp** [comment]
Wrong assumption. I *have* a VG with "precious" LVs and I'd like to use this VG for localpv as well. There's no room for testing if localpv leaves these existing LVs intact.

**Comment by Abhinandan-Purkait** [comment]
@mnlipp LocalPV leaves those existing LVs intact and it's safe to have them. However that would be considered as part of capacity calculation as expected.

**Comment by Abhinandan-Purkait** [comment]
Closing this issue, @mnlipp please feel free to reopen it if you have any more queries. Thank you.
