### ISSUE TITLE
LVMVolume specifies fields with boolean meaning as string

### ISSUE THREAD

**Issue by Thor77** [openebs/lvm-localpv#215]
**Describe the problem/challenge you have**
Due to some preprocessing we're doing on rendered YAML files I discovered an issue with that process in combination with the helm-charts provided in this repository.

Is there a reason the fields `shared` and `thinProvision` of the `LVMVolume` resource are strings accepting yes/no instead of booleans?
This might be confusing when creating them manually as yes/no without quotes are automatically converted to booleans in YAML 1.1

**Describe the solution you'd like**
Change the type of the fields `shared` and `thinProvision` of the `LVMVolume` resource to boolean

**Environment:**
- LVM Driver version: 1.0.0

**Comment by abhilashshetty04** [comment]
@Thor77 , Thanks for reporting the issue. Unfortunately, we dont have plans to modify CR fields. It has many dependencies as well.
