### ISSUE TITLE
Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock

### ISSUE THREAD

**Issue by YangLoveYing** [openebs/lvm-localpv#217]
the openebs-lvm-controller is running, but when I see the log of this pod. It always reminds me "still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock. I occured this issue in physical machine, virtual machine doesn't occur. could you help me, thanks

**Comment by Abhinandan-Purkait** [comment]
Hey @YangLoveYing Can you please share the the environment, machine, details. Also can you share the steps that led you into this?

**Comment by YangLoveYing** [comment]
邮件我已收到，谢谢

**Comment by dsharma-dc** [comment]
@YangLoveYing Please provide the details requested earlier in case you still have this issue. In case it is resolved, please confirm.

**Comment by YangLoveYing** [comment]
邮件我已收到，谢谢

**Comment by avishnu** [comment]
@YangLoveYing unable to reproduce the issue. Please check with the latest release. Closing this for now. If it persists, you can re-open, but you need to provide the details as suggested by @dsharma-dc and @Abhinandan-Purkait .

**Comment by YangLoveYing** [comment]
邮件我已收到，谢谢
