### ISSUE TITLE
cannot mount pvc

### ISSUE THREAD

**Issue by th-2021** [openebs/lvm-localpv#219]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.]
Setup from README.
Used with minio.
Containers stays in ContainerCreating
kubectl get events shows:
~~~
thiller@tom-ml351:~/WORK$ kubectl -n gitlab get events
LAST SEEN   TYPE      REASON        OBJECT                    MESSAGE
3m54s       Warning   FailedMount   pod/gitlab-ml351-ss-0-0   MountVolume.SetUp failed for volume "pvc-3612c5f5-139f-4169-b577-e71e588181fb" : applyFSGroup failed for vol pvc-3612c5f5-139f-4169-b577-e71e588181fb: lstat /var/snap/microk8s/common/var/lib/kubelet/pods/6931a557-8030-4467-8470-83dcbbb692bb/volumes/kubernetes.io~csi/pvc-3612c5f5-139f-4169-b577-e71e588181fb/mount: no such file or directory
~~~
When I create the mount directory manually, the pod continues and enters Running.

**What did you expect to happen:**
mounting should work without intervention.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other [Pastebin](https://pastebin.com/) is fine.)

* `kubectl logs -f openebs-lvm-controller-0 -n kube-system -c openebs-lvm-plugin`
* `kubectl logs -f openebs-lvm-node-[xxxx] -n kube-system -c openebs-lvm-plugin`
* `kubectl get pods -n kube-system`
* `kubectl get lvmvol -A -o yaml`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- LVM Driver version
latest
- Kubernetes version (use `kubectl version`):
1.26.0
- Kubernetes installer & version:
microk8s
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
ubuntu 22.04

**Comment by abhilashshetty04** [comment]
@th-2021 Are you still facing the issue? We cant find any logs in the links that you provided. If issue persists, Can you upload logs again?

**Comment by th-2021** [comment]
I solved it by starting over.
