### ISSUE TITLE
[helm] Support kubernetes 1.27

### ISSUE THREAD

**Issue by jouve** [openebs/lvm-localpv#228]
**Describe the problem/challenge you have**

kubernetes 1.27 dropped [CSIStorageCapacity v1beta1](https://kubernetes.io/blog/2023/03/17/upcoming-changes-in-kubernetes-v1-27/#api-removals-and-other-changes-for-kubernetes-v1-27)   

**Describe the solution you'd like**

upgrade external-provisioner to at least [3.2](https://github.com/kubernetes-csi/external-provisioner/blob/v3.2.0/CHANGELOG/CHANGELOG-3.2.md)

**Anything else you would like to add:**

workaround with the following helm values (using the new registry.k8s.io too):
``` 
provisioner:
    image:
      registry: registry.k8s.io/
      tag: v3.5.0
``` 

**Environment:**

- Kubernetes version (use `kubectl version`): v1.27.1
- Kubernetes installer & version: kubeadm
- helm chart: lvm-localpv  1.0.1

**Comment by Abhinandan-Purkait** [comment]
@jouve Thanks for raising this. Closing this as this has been fixed now.
