### ISSUE TITLE
CICD issue

### ISSUE THREAD

**Issue by houwenchen** [openebs/lvm-localpv#239]
in unit-test:
Upload Coverage Report step can't get file to analysis.

like https://github.com/openebs/lvm-localpv/actions/runs/5109654062/jobs/9184670017 shows:
==> Searching for coverage reports in:
    + .
--> No coverage report found.
    Please visit http://docs.codecov.io/docs/supported-languages

**Comment by houwenchen** [comment]
I have forked this project, but don't have access to raise a pr.

**Comment by abhilashshetty04** [comment]
@houwenchen , Thanks for reporting the issue. Could you provide more context on this.

**Comment by abhilashshetty04** [comment]
@houwenchen , We assume issue has not resurfaced. We will close this for now. Please recreate issue incase you encounter it again.

**Comment by abhilashshetty04** [comment]
@houwenchen We do see that code coverage report in CodeCov job run. We will look into this.

**Comment by houwenchen** [comment]
@abhilashshetty04 Hi, I raise a pr to love this issue. 
https://github.com/openebs/lvm-localpv/pull/266

**Comment by niladrih** [comment]
https://github.com/openebs/lvm-localpv/pull/285 fixes this.
