### ISSUE TITLE
openebs/lvm-driver image name and tag are not separated by colon in generated manifest

### ISSUE THREAD

**Issue by meise** [openebs/lvm-localpv#246]
**What steps did you take and what happened:**

1. `kubectl apply -f https://openebs.github.io/charts/lvm-operator.yaml`
2. Results in:
```
NAME                       READY   STATUS         RESTARTS   AGE
openebs-lvm-controller-0   4/5     ErrImagePull   0          6s
```

```
  Warning  Failed     9s    kubelet            Failed to pull image "openebs/lvm-driver1.2.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/openebs/lvm-driver1.2.0:latest": failed to resolve reference "docker.io/openebs/lvm-driver1.2.0:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**What did you expect to happen:**

`openebs/lvm-driver` reference should be `openebs/lvm-driver:1.2.0`  and not `openebs/lvm-driver1.2.0` in [manifest file](https://openebs.github.io/charts/lvm-operator.yaml).

Wrong reference in:
* openebs-lvm-controller
* openebs-lvm-node

**Environment:**
- LVM Driver version 1.2.0

**Comment by skvishy27** [comment]
Getting same error
Warning  Failed     25m (x2 over 25m)    kubelet            Error: ErrImagePull
  Warning  Failed     25m (x2 over 25m)    kubelet            Error: ImagePullBackOff
  Normal   Pulling    24m (x3 over 25m)    kubelet            Pulling image "openebs/lvm-driver1.2.0"
  Warning  Failed     24m (x3 over 25m)    kubelet            Failed to pull image "openebs/lvm-driver1.2.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/openebs/lvm-driver1.2.0:latest": failed to resolve reference "docker.io/openebs/lvm-driver1.2.0:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
  Normal   BackOff    25s (x110 over 25m)  kubelet            Back-off pulling image "openebs/lvm-driver1.2.0"

**Comment by niladrih** [comment]
This is fixed.
