### ISSUE TITLE
Update docs to indicate preferred versions of some build dependencies

### ISSUE THREAD

**Issue by kro-cat** [openebs/lvm-localpv#248]
**Describe the problem/challenge you have**
When following the docs, it's not readily obvious what the required go packages and their preferred versions are. For example, controller-gen may need to be installed before running `make`, but the latest version of that program is incompatible with this repository's code. The absence of some dependencies may cause a build or a test step to fail, as they may not be installed automatically.

**Describe the solution you'd like**
It may be useful to indicate build deps and their preferred versions (if any) in `docs/developer-setup.md`:
> ...
> ### Building and Testing your changes
> 
> * install go build dependencies:
>   * golangci-lint
>   * sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.0
>   * ginkgo ( needed for `make ci` )
> 
> * run `make` in the top directory. It will:
>   * Build the binary.
> ...

**Anything else you would like to add:**
`sigs.k8s.io/controller-tools/cmd/controller-gen@v0.6.0` appears to work, as well.

**Comment by kro-cat** [comment]
I figured I should open up a new issue for this instead of including it in an unrelated PR.

**Comment by kro-cat** [comment]
Maybe it would be wise to contribute some more explicit build steps or practices. It took me a while to figure out the following build procedure for minikube on a local dev system:

```sh
# make sure docker is running first...

# link minikube with docker
minikube start
eval $(minikube docker-env)

# install build deps
make install-golangci-lint
make verify-deps
go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.0
go install github.com/onsi/ginkgo/ginkgo@latest
# install musl-gcc toolchain b/c we're building for alpine...

# build <- iterate here
CC=musl-gcc make

# push image to minikube if modified
minikube image load "openebs/lvm-driver:ci" --overwrite=true

# run ci tests
make ci

# investigate here...

# cleanup ci tests
sudo rm /tmp/disk.img
losetup -l | grep '(deleted)' | awk '{print $1}' | xargs -I{} sudo losetup -d {}
kubectl delete -f deploy/sample/lvmsnapclass.yaml
kubectl delete -f deploy/lvm-operator.yaml

# iterate if needed
```

**Comment by Abhinandan-Purkait** [comment]
@kro-cat Can you please explain what changes are you planning on this issue? Is it refactoring the docs to include the build deps?

**Comment by kro-cat** [comment]
> @kro-cat Can you please explain what changes are you planning on this issue? Is it refactoring the docs to include the build deps?

@Abhinandan-Purkait Sorry for the wait, it's been a busy month for me.
I think, yeah, that's the best way to describe what I'd like to see. Refactoring the build docs to describe build and test dependencies (controller-gen, ginkgo, musl-gcc). That would help with local development. I also think documenting those make targets (install-golangci-lint and verify-deps) in the same area as build & test deps would be necessary too, since those targets will automatically install some dependencies.

**Comment by Abhinandan-Purkait** [comment]
Sounds good. @kro-cat Would you mind raising a PR or probably explain so that someone can pick it up?

**Comment by abhilashshetty04** [comment]
Hi @kro-cat , We will proceed with the closure of this ticket. Please let us know If you want to reopen it or create a new ticket incase you need further help.
