### ISSUE TITLE
installation failure of the latest lvm-operator.yaml 

### ISSUE THREAD

**Issue by cnut** [openebs/lvm-localpv#251]
**What steps did you take and what happened:**

```bash
kubectl apply -f https://openebs.github.io/charts/lvm-operator.yaml
```
when I used the command above to install lvm-localpv, I encountered installation failure.

```
kubectl describe pod openebs-lvm-node-rh5gd -n kube-system
...
  Normal   Pulling    14s   kubelet            Pulling image "openebs/lvm-driver1.2.0"
  Warning  Failed     12s   kubelet            Failed to pull image "openebs/lvm-driver1.2.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/openebs/lvm-driver1.2.0:latest": failed to resolve reference "docker.io/openebs/lvm-driver1.2.0:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
...

```

it seems there is a typo for `image: openebs/lvm-driver1.2.0`, I changed it to `openebs/lvm-driver:1.2.0`, this problem will be fixed.

**What did you expect to happen:**
after executing `kubectl apply -f https://openebs.github.io/charts/lvm-operator.yaml`, the lvm-localpv is installed successfully.

**Comment by abhilashshetty04** [comment]
@cnut , Thanks for reporting it. Its a known issue. We will fix this.

**Comment by Abhinandan-Purkait** [comment]
This has been fixed.
