### ISSUE TITLE
helm lint fails due to extra hyphen in if statement

### ISSUE THREAD

**Issue by cmontemuino** [openebs/lvm-localpv#271]
**What steps did you take and what happened:**

```bash
git clone git@github.com:openebs/lvm-localpv.git
git checkout lvm-localpv-1.3.0
cd deploy/helm/charts
helm lint .
```

Output:

```text
==> Linting .
[ERROR] templates/rbac.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: v1

Error: 1 chart(s) linted, 1 chart(s) failed
```

**What did you expect to happen:**

I would expect this output instead:

```text
==> Linting .

1 chart(s) linted, 0 chart(s) failed
```

**Anything else you would like to add:**

Offending code: https://github.com/openebs/lvm-localpv/blob/400159dad72980818fe9bad01a53d383afa20466/deploy/helm/charts/templates/rbac.yaml#L126

```yaml
{{- if .Values.serviceAccount.lvmNode.create -}}
```

The hyphen before the closing brackets is chomping all the whitespace after the brackets.

I'd like to open a PR with the fix.

**Environment:**

> **Not applicable**

- LVM Driver version
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by abhilashshetty04** [comment]
Hi @cmontemuino , Thanks for creating the issue. Please go ahead and raise the PR.

**Comment by cmontemuino** [comment]
> Hi @cmontemuino , Thanks for creating the issue. Please go ahead and raise the PR.

Here it is: https://github.com/openebs/lvm-localpv/pull/272
