### ISSUE TITLE
chart v1.5.0

### ISSUE THREAD

**Issue by WMP** [openebs/lvm-localpv#291]
In tar.gz package on release 1.5.0 https://github.com/openebs/lvm-localpv/releases/tag/v1.5.0 in deploy/helm/chart is version 1.4.0. Additional, in helm repo newest version is also 1.4.0:
```
my:~/$ helm repo update openebs-lvmlocalpv
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "openebs-lvmlocalpv" chart repository
Update Complete. ⎈Happy Helming!⎈
my:~/$ helm search repo openebs-lvmlocalpv/lvm-localpv --versions
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                       
openebs-lvmlocalpv/lvm-localpv  1.4.0           1.4.0           CSI Driver for dynamic provisioning of LVM Pers...
openebs-lvmlocalpv/lvm-localpv  1.3.1           1.3.0           CSI Driver for dynamic provisioning of LVM Pers...
openebs-lvmlocalpv/lvm-localpv  1.3.0           1.3.0           CSI Driver for dynamic provisioning of LVM Pers...
my:~/$ helm pull --untar openebs-lvmlocalpv/lvm-localpv --version 1.5.0
Error: chart "lvm-localpv" matching 1.5.0 not found in openebs-lvmlocalpv index. (try 'helm repo update'): no chart version found for lvm-localpv-1.5.0
my:~/$ 
```

**Comment by Abhinandan-Purkait** [comment]
@WMP We had some issues on 1.5.0 release thats why we had to retract the release. We now have released 1.5.1 lvm helm chart, you might want to check that out.

**Comment by dsharma-dc** [comment]
The openEBS project has been restructured recently and it is now recommended to use the umbrella chart for installation of the LVM engine too. Please follow the instructions at https://openebs.io/docs/quickstart-guide/installation and let us know if there are any questions or you run into any issue.

**Comment by dsharma-dc** [comment]
I'll go ahead closing this issue now referring the last comment as suggestion for the user. Please feel free to update if there is still some trouble w.r.t installation after referring new docs.
