### ISSUE TITLE
If a task is suspended, workers are occupied and subsequent task execution is blocked.

### ISSUE THREAD

**Issue by redriverhong** [openebs/lvm-localpv#298]
https://github.com/openebs/lvm-localpv/blob/cd7e9b745dd5bbb5ad471035e3c3baf8cade13fc/pkg/mgmt/volume/volume.go#L326
If a task is suspended, workers are occupied and subsequent task execution is blocked.
Indicates whether it is necessary to add the task execution timeout control. The execution of LVS-related commands in the process is suspended in some fault scenarios.

**Comment by abhilashshetty04** [comment]
@redriverhong , Thanks for posting the issue.
Could you please point out a scenario where you see the task being suspended. Is it easily reproducible?

**Comment by dsharma-dc** [comment]
As requested earlier, it would be nice to know if this issue is reported based on some problem faced ? If yes, please provide those scenario details.

**Comment by dsharma-dc** [comment]
Closing this issue for now. Please feel free to reopen with more details as requested if there is a potential problem scenario identified.
