### ISSUE TITLE
support resize for LVM

### ISSUE THREAD

**Issue by pawanpraka1** [openebs/lvm-localpv#3]
**Describe the problem/challenge you have**

Support resize for lvm volumes.

**Comment by sonasingh46** [comment]
@pawanpraka1 -- I would like to work on this issue. If you have any pointers/relevant doc on this one, please point me to that.

**Comment by pawanpraka1** [comment]
@sonasingh46 there is already a PR for this one https://github.com/openebs/lvm-localpv/pull/4.

**Comment by sonasingh46** [comment]
Ok. I was not aware. At least, I can review.
