### ISSUE TITLE
Add more CI tests

### ISSUE THREAD

**Issue by dsharma-dc** [openebs/lvm-localpv#311]
**Describe the problem/challenge you have**
We need to increase the CI tests coverage scenario. 

**Describe the solution you'd like**
Add more tests to be run via CI testing script.

**Anything else you would like to add:**
We'll be initially covering scenarios like thinpool extension, snapshots, vgpattern, and add more as and when we keep discovering more scenarios.

**Environment:**
- LVM Driver version
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by dsharma-dc** [comment]
Current PRs created:
PR #308 
PR #309 
PR #310

**Comment by dsharma-dc** [comment]
PR https://github.com/openebs/lvm-localpv/pull/315

**Comment by dsharma-dc** [comment]
PR https://github.com/openebs/lvm-localpv/pull/320

**Comment by abhilashshetty04** [comment]
PR https://github.com/openebs/lvm-localpv/pull/323

**Comment by avishnu** [comment]
Closing this as completed.
