### ISSUE TITLE
EXT4-fs (dm-3): Couldn't mount because of unsupported optional features (2000)

### ISSUE THREAD

**Issue by jax-wong** [openebs/lvm-localpv#342]
**What steps did you take and what happened:**
pvcreate /dev/sdc
vgcreate lvmvg /dev/sdc

1.StorageClass, pv and pvc is ready , but the pod is in ContainerCreating.
2.dmesg -T: shows "EXT4-fs (dm-3): Couldn't mount because of unsupported optional features (2000)"

kd pod {podid}:
![image](https://github.com/user-attachments/assets/e73dd568-f8ad-4210-97e5-c8558a8f927b)

**Environment:**
- LVM Driver version : kubectl apply -f https://openebs.github.io/charts/lvm-operator.yaml
- Kubernetes version (use `kubectl version`): 1.23
- Cloud provider or hardware configuration:  linux kernel 3.10.0
- OS (e.g. from `/etc/os-release`): redhat7.6 

wonder if  it is caused by the kernel not supporting ? Thank u

**Comment by jax-wong** [comment]
sloved.
this tip is true！
![image](https://github.com/user-attachments/assets/f4bfb56d-e458-4fa0-a06b-f551a376503f)

**Comment by tiagolobocastro** [comment]
Seems your kernel does not support the features being used.
But yes, installation via operator is not the supported way indeed.
