### ISSUE TITLE
not a bug, just incredibly confusing doc. 

### ISSUE THREAD

**Issue by kundeng** [openebs/lvm-localpv#343]
The doc now says you shouldn't provision the lvm volume group etc.  Is that true for lvm-localpv?  
How do I tell it which disks it should touch!

**Comment by tiagolobocastro** [comment]
Hi, that seems wrong indeed, which doc are you referring to?

**Comment by kundeng** [comment]
Right in the README with typos:
```
This is the old maual config process
LocalPV-LVM will num dynamically provision the VG fro you
The PV, VG and LV names will be dynamically provisioned by OpenEBS LocalPV-LVM as K8s unique entities (for safety, you cannot provide your own PV, VG or LV names)
```

**Comment by tiagolobocastro** [comment]
Indeed :(
Would you like to raise a PR fixing that?
