### ISSUE TITLE
Can lvm localpv be integrated with Nomad for use? I couldn't find any relevant documents within the project

### ISSUE THREAD

**Issue by ESonata** [openebs/lvm-localpv#345]
I want to use lvm localpv as a CSI plugin in Nomad. Is it currently supported?

**Comment by dsharma-dc** [comment]
Could you elaborate on use-case and the volume requirements?  I don't think this has ever been tested with Nomad.

**Comment by dsharma-dc** [comment]
Please confirm if you would be able to share more details w.r.t this use-case.

**Comment by dsharma-dc** [comment]
Closing for now. Please reopen with more details if needed.
