### ISSUE TITLE
CSIDriver is missing fsGroupPolicy

### ISSUE THREAD

**Issue by mazocode** [openebs/lvm-localpv#62]
**What steps did you take and what happened:**
Created a new volume with fsGroup specified on pod spec securityContext but permissions were root:root 0755

**What did you expect to happen:**
Filesystem mounted with group set to GID specified in fsGroup.

**Anything else you would like to add:**

The CSIDriver is missing fsGroupPolicy: File

**Environment:**
- lvm-localpv version: 0.4.0

**Comment by pawanpraka1** [comment]
@mazocode what is the k8s version you are using? Fsgroup policy is in alpha in k8s 1.19 and it is in beta in k8s 1.20. If you are already using k8s with fsgroup policy enabled then please check if storage class's has fstype mentioned (see the similar discussion in the other repo https://github.com/openebs/zfs-localpv/issues/282). The default fsGroupPolicy is ReadWriteOnceWithFSType if not mentioned in the CSIDriver spec.

https://kubernetes-csi.github.io/docs/support-fsgroup.html.

**Comment by mazocode** [comment]
I am using 1.20.2 and the storageclass has fsType: ext4. I could not get fsGroup working without  setting the fsGroupPolicy manually on the driver.

**Comment by pawanpraka1** [comment]
Can you set the policy to ReadWriteOnceWithFSType and see if it is working? Another thing we can try is use fstype parameter instead of fsType in the storage class (not sure if this will work but k8s could be looking for fstype string possibly).

**Comment by pawanpraka1** [comment]
@mazocode did you try the above steps?

**Comment by mazocode** [comment]
Unfortunately, there are already volumes created referencing the driver. I will try this on another cluster, but this may take some time.

**Comment by pawanpraka1** [comment]
@mazocode sure. Let me know if you need any help.

**Comment by joshuacox** [comment]
@pawanpraka1 can you post an example yaml file for the storage class with the fsGroupPolicy specified?

I hamhandedly tried:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvmpv
spec:
  fsGroupPolicy: File
parameters:
  storage: "lvm"
  volgroup: "lvmpv-vg"
provisioner: local.csi.openebs.io
```

**Comment by pawanpraka1** [comment]
@joshuacox can you try this storageclass yaml
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvmpv
parameters:
  storage: "lvm"
  fstype: ext4
  volgroup: "lvmpv-vg"
provisioner: local.csi.openebs.io
```

**Comment by pawanpraka1** [comment]
we have made the change in the CSi driver to set default fstype to ext4 if not mentioned in the storageclass.With the release of v0.6, fsgrouppolicy should work for the storageclasses which does not have fstype. Closing this issue. Please reopen if you guys are facing any issue.

**Comment by tavrez** [comment]
I started to work with zfs local pv on one of my clusters and encountered this problem, tried to above steps, didn't work. Can you help me if I'm doing anything wrong?
```bash
# kubectl get csidriver zfs.csi.openebs.io -o yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  annotations:
    meta.helm.sh/release-name: zfs
    meta.helm.sh/release-namespace: zfs-localpv
  creationTimestamp: "2025-10-08T13:14:17Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: zfs-localpv
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: zfs.csi.openebs.io
  resourceVersion: "227111887"
  uid: 95fa9c25-d13f-44ae-8846-0b4e81316cb4
spec:
  attachRequired: false
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: false
  requiresRepublish: false
  seLinuxMount: false
  storageCapacity: true
  volumeLifecycleModes:
  - Persistent
# kubectl get sc zfs -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2025-10-09T16:16:47Z"
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: zfs
  resourceVersion: "227445165"
  uid: 7ab460d9-3737-4eef-89a5-4a8dd0353185
parameters:
  fstype: zfs
  poolname: tank0/k8s-pvc
  recordsize: 128k
provisioner: zfs.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
zfs-localpv version is 2.8.0
kubernetes version is 1.29.15
I do this:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  namespace: test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: zfs
---
apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: test
spec:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  containers:
  - name: test
    image: node:alpine
    command: [ "tail", "-f", "/dev/null"]
    volumeMounts:
    - mountPath: "/data"
      name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: test
```
But I receive error:
```
# kubectl describe pod test -n test
Events:
  Type     Reason       Age               From               Message
  ----     ------       ----              ----               -------
  Normal   Scheduled    13s               default-scheduler  Successfully assigned test/test to server
  Warning  FailedMount  5s (x5 over 13s)  kubelet            MountVolume.SetUp failed for volume "pvc-9f5c6c1e-1e4a-4008-978b-bf895b6641a1" : applyFSGroup failed for vol pvc-9f5c6c1e-1e4a-4008-978b-bf895b6641a1: lstat /var/snap/microk8s/common/var/lib/kubelet/pods/490a052a-38d0-41f5-b1ab-29113a0a679c/volumes/kubernetes.io~csi/pvc-9f5c6c1e-1e4a-4008-978b-bf895b6641a1/mount: no such file or directory
```
