### ISSUE TITLE
add migration of disk to different node for LVM LocalPV

### ISSUE THREAD

**Issue by pawanpraka1** [openebs/lvm-localpv#74]

**Comment by dsharma-dc** [comment]
Not clear of this requirement. It would be good to have details around the requirement and rationale.

**Comment by dsharma-dc** [comment]
Potential use case: A disk having some volume group is moved to a different node/host and the user would want to import the volume group present on the drive after the disk is attached to the new node/host.

**Comment by dsharma-dc** [comment]
This isn't prioritised for product inclusion or scoping yet.

**Comment by avishnu** [comment]
@pawanpraka1 can you provide more clarity on this issue as description is missing? Does #314 cover this requirement?

**Comment by avishnu** [comment]
Tracking this via #314
