### ISSUE TITLE
Enable monitoring on thin pool to allow auto-extend threshold automatically 

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/lvm-localpv#93]
**Describe the problem/challenge you have**
- Automatic extension requires **dmeventd** (device mapper event daemon) service to be running to continuously monitor the LVs
But in case of container based LVM is not able to communicate with dmeventd service, the monitoring gets disable, and auto extend of thin pools did not work as expected.
```  
 $ lvs -o+seg_monitor 
  LV               VG       Attr           LSize   Pool   ....          Monitor    
  lvmvg_thinpool  lvmvg  twi-aotz--        2.07g          ....          not monitored   
```
-  For a workaround currently its requires monitoring to be explicitly enabled once from the host node, on per thin pool bases. 
```sh
$ lvchange --monitor y vg-name/lvmvg_thinpool
```
-  Without this step, automatic extension of the logical thin pool will not occur, regardless of any settings in the `lvm.conf`.

**Describe the solution you'd like**
We need to find a way to communicate to the `dmeventd` service from `lvm-csi-plugin` container , which will help to automatically enable the monitoring and no manual action required.

**Comment by ianroberts** [comment]
> * For a workaround currently its requires monitoring to be explicitly enabled once from the host node, on per thin pool bases.
> 
> ```shell
> $ lvchange --monitor y vg-name/lvmvg_thinpool
> ```

... and this command can only be run _after_ the first LVM local PV has been provisioned on that particular node.  If I try to enable monitoring on a node where the thin pool exists but has not yet had any local PVs provisioned on it, I get

```
# lvchange --monitor y localhd/localhd_thinpool
  Logical volume localhd/localhd_thinpool is not active.
```

**Comment by andrey-podko** [comment]
@ianroberts Funny fact: Piraeus/linbit has same behavior - first creation of thin volume on thinpool disables "monitor" option

**Comment by dsharma-dc** [comment]
This has been looked at recently while starting to add some new CI test around thin provisioning. I'd think that a good reason to not automatically enable monitoring on thinpool is that some users may not want to have thinpool grow automatically or grow beyond a certain limit. There is no config in lvm.conf to define a cap/limit of auto-extend. e.g. on a 10G VG, they may not want a 5G thinpool to grow beyond 7G. I don't see a way to restrict that. Hence, users can manually enable monitoring depending on the use case and required behaviour of thinpool.

**Comment by ianroberts** [comment]
That's fair enough, but this should be highlighted in the documentation, particularly given my experience that you can't enable monitoring until _after_ the first thin LV has been allocated within the thin pool.  I wonder also if you have a thin pool where monitoring has been enabled and then you delete the last LV from that pool, does monitoring remain enabled when a new LV is subsequently created or does the pool go "inactive" and monitoring have to be re-enabled manually?

**Comment by dsharma-dc** [comment]
@ianroberts 
> I wonder also if you have a thin pool where monitoring has been enabled and then you delete the last LV from that pool, does monitoring remain enabled when a new LV is subsequently created or does the pool go "inactive" and monitoring have to be re-enabled manually?

The monitoring remains enabled on the thinpool after the last LV is deleted from it.
```
$ sudo lvs -o+seg_monitor
  LV                                       VG   Attr       LSize   Pool          Origin Data%  Meta%  Move Log Cpy%Sync Convert Monitor  
  dsvg_thinpool                            dsvg twi-aotz-- 500.00m                      0.00   11.04                            monitored
  pvc-77175183-c58c-4751-b75b-163de245160c dsvg Vwi-a-tz-- 500.00m dsvg_thinpool        0.00                                             
  pvc-e55df1ea-3cd6-47c6-b929-1dace1b09d6e dsvg Vwi-a-tz-- 500.00m dsvg_thinpool        0.00         
                                    
$ kubectl delete -f ../yamls/lvm_pvc.yaml
persistentvolumeclaim "csi-lvmpv-ds-1" deleted
persistentvolumeclaim "csi-lvmpv-ds-2" deleted

$ sudo lvs -o+seg_monitor
  LV            VG   Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert Monitor  
  dsvg_thinpool dsvg twi-aotz-- 500.00m             0.00   10.84                            monitored
```

**Comment by balaharish7** [comment]
This is documented in [PR #457](https://github.com/openebs/website/pull/457).

**Comment by dsharma-dc** [comment]
Closing this issue since the documentation has been updated. Auto enablement of monitoring on thinpool will not be taken up as a near term goal.
